version: "3.9"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    depends_on:
      - db

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head; uvicorn main:app --host 0.0.0.0"
    volumes:
      - ./src/:/app
    ports:
      - 8000:8000
    restart: always
    env_file:
      - .env
    depends_on:
      - db
